/**
 * Strapi CMS E2B Template
 *
 * This template provides a headless Strapi CMS backend that runs alongside
 * the frontend application in the E2B sandbox.
 */

export const template = {
  name: "strapi",
  description:
    "Strapi headless CMS backend with auto-generated content types from blueprint",

  // Base configuration
  nodeVersion: "20",
  port: 1337,

  // Files to be written to the sandbox
  files: {
    "package.json": JSON.stringify(
      {
        name: "strapi-backend",
        version: "0.1.0",
        private: true,
        description: "Strapi CMS backend for VibeHub",
        scripts: {
          develop: "strapi develop",
          start: "strapi start",
          build: "strapi build",
          "strapi": "strapi",
        },
        dependencies: {
          "@strapi/strapi": "5.4.0",
          "@strapi/plugin-users-permissions": "5.4.0",
          "@strapi/plugin-i18n": "5.4.0",
          "better-sqlite3": "9.6.0",
          react: "^18.0.0",
          "react-dom": "^18.0.0",
          "react-router-dom": "^6.0.0",
          "styled-components": "^6.0.0",
        },
        devDependencies: {},
        engines: {
          node: ">=18.0.0 <=22.x.x",
          npm: ">=6.0.0",
        },
        strapi: {
          uuid: "vibehub-strapi-template",
        },
      },
      null,
      2,
    ),

    // Strapi configuration
    "config/admin.ts": `export default {
  auth: {
    secret: env('ADMIN_JWT_SECRET', 'default-secret-change-in-production'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT', 'default-salt-change-in-production'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT', 'default-transfer-salt'),
    },
  },
  flags: {
    nps: false,
    promoteEE: false,
  },
};`,

    "config/server.ts": `export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS', ['key1', 'key2']),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});`,

    "config/database.ts": `export default ({ env }) => ({
  connection: {
    client: 'sqlite',
    connection: {
      filename: env('DATABASE_FILENAME', '.tmp/data.db'),
    },
    useNullAsDefault: true,
    debug: false,
  },
});`,

    "config/middlewares.ts": `export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];`,

    "config/plugins.ts": `export default {
  'users-permissions': {
    config: {
      jwtSecret: env('JWT_SECRET', 'default-jwt-secret'),
    },
  },
};`,

    // Environment configuration
    ".env.example": `# Server
HOST=0.0.0.0
PORT=1337

# Secrets
APP_KEYS=key1,key2
API_TOKEN_SALT=your-api-token-salt
ADMIN_JWT_SECRET=your-admin-jwt-secret
TRANSFER_TOKEN_SALT=your-transfer-token-salt
JWT_SECRET=your-jwt-secret

# Database
DATABASE_FILENAME=.tmp/data.db

# CORS - Allow frontend access
CORS_ORIGIN=*`,

    ".env": `HOST=0.0.0.0
PORT=1337
APP_KEYS=key1,key2
API_TOKEN_SALT=api-token-salt
ADMIN_JWT_SECRET=admin-jwt-secret
TRANSFER_TOKEN_SALT=transfer-token-salt
JWT_SECRET=jwt-secret
DATABASE_FILENAME=.tmp/data.db`,

    // TypeScript configuration
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          module: "CommonJS",
          moduleResolution: "node",
          resolveJsonModule: true,
          lib: ["ES2020"],
          target: "ES2019",
          strict: false,
          noImplicitAny: false,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          esModuleInterop: true,
          skipLibCheck: true,
          declaration: true,
          outDir: "./dist",
          rootDir: ".",
        },
        include: ["./", "./**/*.ts", "./**/*.js", "./**/*.json"],
        exclude: ["node_modules", "build", "dist", ".cache"],
      },
      null,
      2,
    ),

    // Placeholder for content types - will be generated by cms_setup node
    "src/api/.gitkeep": "",
    "src/extensions/.gitkeep": "",
    "src/components/.gitkeep": "",
    "public/uploads/.gitkeep": "",
    ".tmp/.gitkeep": "",
  },

  // Build commands
  buildCommands: [
    "npm install",
    "npm run build",
  ],

  // Start command
  startCommand: "npm run develop",

  // Health check endpoint
  healthCheck: {
    path: "/api/health",
    port: 1337,
  },

  // API configuration
  api: {
    basePath: "/api",
    auth: {
      type: "api-token",
      header: "Authorization",
      prefix: "Bearer",
    },
  },
};

export default template;
